name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build-main:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cicada98
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t cicada98/experts:latest
      - name: Push the Docker image
        run: docker push cicada98/experts:latest
