name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build-main:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t cicada98/experts:latest
      - name: Push the Docker image
        run: |
          docker login -u cicada98 -p ${{secrets.DOCKER_HUB_LOGIN}}
          docker push cicada98/experts:latest
