name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build-main:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . -t cicada98/experts:latest
      - name: Push the Docker image
        run: |
          docker push cicada98/experts:latest
